import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useConnect } from 'wagmi';
import { MetaMaskConnector } from 'wagmi/connectors/metaMask';

export default function Home() {
  const { connectAsync } = useConnect();

  const handleAuth = async () => {
    const { account, chain } = await connectAsync({ connector: new MetaMaskConnector() });
    const userData = { address: account, chainId: chain.id };
    console.log(userData);
  };

  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={handleAuth} className={styles.login}>Login using Metamask </button>
    </div>
  )
}


